-- =====================================================================
-- Table: SERVICE_PROCESSING_FAILURE
-- Purpose: Track service processing failures for monitoring and retry
-- Created: Auto-generated for RecurrentServiceService failure tracking
-- =====================================================================

-- Create sequence for primary key
CREATE SEQUENCE SERVICE_PROCESSING_FAILURE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create table to track service processing failures
CREATE TABLE SERVICE_PROCESSING_FAILURE
(
    ID                      NUMBER(19)                  NOT NULL,
    SERVICE_INSTANCE_ID     NUMBER(19),
    USERNAME                VARCHAR2(64)                NOT NULL,
    PLAN_ID                 VARCHAR2(64),
    PLAN_NAME               VARCHAR2(128),
    ERROR_TYPE              VARCHAR2(100),
    ERROR_MESSAGE           VARCHAR2(4000),
    STACK_TRACE             VARCHAR2(4000),
    RETRY_COUNT             NUMBER(10)      DEFAULT 0,
    PROCESSING_STATUS       VARCHAR2(50),
    FAILURE_DATE            TIMESTAMP       DEFAULT SYSTIMESTAMP,
    LAST_RETRY_DATE         TIMESTAMP,
    RESOLVED_DATE           TIMESTAMP,
    BATCH_ID                VARCHAR2(100),
    ADDITIONAL_INFO         VARCHAR2(1000),
    CONSTRAINT PK_SERVICE_PROCESSING_FAILURE PRIMARY KEY (ID)
);

-- Create indexes for better query performance
CREATE INDEX IDX_SPF_USERNAME ON SERVICE_PROCESSING_FAILURE(USERNAME);
CREATE INDEX IDX_SPF_SERVICE_ID ON SERVICE_PROCESSING_FAILURE(SERVICE_INSTANCE_ID);
CREATE INDEX IDX_SPF_STATUS ON SERVICE_PROCESSING_FAILURE(PROCESSING_STATUS);
CREATE INDEX IDX_SPF_BATCH_ID ON SERVICE_PROCESSING_FAILURE(BATCH_ID);
CREATE INDEX IDX_SPF_FAILURE_DATE ON SERVICE_PROCESSING_FAILURE(FAILURE_DATE);

-- Composite index for retry queries
CREATE INDEX IDX_SPF_STATUS_RETRY ON SERVICE_PROCESSING_FAILURE(PROCESSING_STATUS, RETRY_COUNT);

-- Add comments for documentation
COMMENT ON TABLE SERVICE_PROCESSING_FAILURE IS 'Tracks service processing failures during recurrent service reactivation for monitoring and retry purposes';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.ID IS 'Primary key';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.SERVICE_INSTANCE_ID IS 'Foreign key reference to SERVICE_INSTANCE table';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.USERNAME IS 'Username associated with the failed service';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.PLAN_ID IS 'Plan identifier';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.PLAN_NAME IS 'Plan name for easy reference';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.ERROR_TYPE IS 'Exception class name';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.ERROR_MESSAGE IS 'Exception message';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.STACK_TRACE IS 'Full stack trace of the exception';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.RETRY_COUNT IS 'Number of retry attempts';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.PROCESSING_STATUS IS 'Status: FAILED, PENDING_RETRY, RESOLVED';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.FAILURE_DATE IS 'Timestamp when failure occurred';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.LAST_RETRY_DATE IS 'Timestamp of last retry attempt';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.RESOLVED_DATE IS 'Timestamp when failure was resolved';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.BATCH_ID IS 'Batch processing run identifier';
COMMENT ON COLUMN SERVICE_PROCESSING_FAILURE.ADDITIONAL_INFO IS 'Additional context information';

-- Grant permissions (adjust as needed for your environment)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICE_PROCESSING_FAILURE TO <your_app_user>;
-- GRANT SELECT ON SERVICE_PROCESSING_FAILURE_SEQ TO <your_app_user>;
