-- =====================================================================
-- History tables for SERVICE_INSTANCE and BUCKET_INSTANCE.
-- Records archived here when the scheduler deletes the originals
-- (CYCLE_END_DATE or EXPIRY_DATE landed on yesterday).
-- =====================================================================

CREATE SEQUENCE SERVICE_INSTANCE_HISTORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE SERVICE_INSTANCE_HISTORY
(
    ID                       NUMBER(19)        NOT NULL,
    ORIGINAL_ID              NUMBER(19)        NOT NULL,
    PLAN_ID                  VARCHAR2(64)      NOT NULL,
    PLAN_NAME                VARCHAR2(64)      NOT NULL,
    PLAN_TYPE                VARCHAR2(64)      NOT NULL,
    RECURRING_FLAG           NUMBER(1)         NOT NULL,
    USERNAME                 VARCHAR2(64)      NOT NULL,
    CYCLE_START_DATE         TIMESTAMP,
    CYCLE_END_DATE           TIMESTAMP,
    NEXT_CYCLE_START_DATE    TIMESTAMP,
    SERVICE_START_DATE       TIMESTAMP         NOT NULL,
    EXPIRY_DATE              TIMESTAMP         NOT NULL,
    STATUS                   VARCHAR2(64)      NOT NULL,
    ORIGINAL_CREATED_AT      TIMESTAMP,
    ORIGINAL_UPDATED_AT      TIMESTAMP,
    REQUEST_ID               VARCHAR2(255)     NOT NULL,
    IS_GROUP                 NUMBER(1),
    DELETION_REASON          VARCHAR2(64)      NOT NULL,
    ARCHIVED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    BATCH_ID                 VARCHAR2(100),
    CONSTRAINT PK_SERVICE_INSTANCE_HISTORY PRIMARY KEY (ID)
);

CREATE INDEX IDX_SIH_ORIGINAL_ID  ON SERVICE_INSTANCE_HISTORY(ORIGINAL_ID);
CREATE INDEX IDX_SIH_USERNAME     ON SERVICE_INSTANCE_HISTORY(USERNAME);
CREATE INDEX IDX_SIH_BATCH_ID     ON SERVICE_INSTANCE_HISTORY(BATCH_ID);
CREATE INDEX IDX_SIH_ARCHIVED_AT  ON SERVICE_INSTANCE_HISTORY(ARCHIVED_AT);

COMMENT ON TABLE SERVICE_INSTANCE_HISTORY
    IS 'Audit history of SERVICE_INSTANCE rows deleted by the scheduler.';

CREATE SEQUENCE BUCKET_INSTANCE_HISTORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE BUCKET_INSTANCE_HISTORY
(
    ID                          NUMBER(19)     NOT NULL,
    ORIGINAL_ID                 NUMBER(19)     NOT NULL,
    BUCKET_ID                   VARCHAR2(64)   NOT NULL,
    SERVICE_ID                  NUMBER(19),
    BUCKET_TYPE                 VARCHAR2(64),
    RULE                        VARCHAR2(64),
    PRIORITY                    NUMBER(19),
    INITIAL_BALANCE             NUMBER(19),
    CURRENT_BALANCE             NUMBER(19),
    USAGE                       NUMBER(19),
    CARRY_FORWARD               NUMBER(1),
    MAX_CARRY_FORWARD           NUMBER(19),
    TOTAL_CARRY_FORWARD         NUMBER(19),
    CARRY_FORWARD_VALIDITY      NUMBER(10),
    TIME_WINDOW                 VARCHAR2(64),
    CONSUMPTION_LIMIT           NUMBER(19),
    CONSUMPTION_LIMIT_WINDOW    VARCHAR2(64),
    EXPIRATION                  TIMESTAMP,
    ORIGINAL_UPDATED_AT         TIMESTAMP,
    IS_UNLIMITED                NUMBER(1),
    DELETION_REASON             VARCHAR2(64)   NOT NULL,
    ARCHIVED_AT                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    BATCH_ID                    VARCHAR2(100),
    CONSTRAINT PK_BUCKET_INSTANCE_HISTORY PRIMARY KEY (ID)
);

CREATE INDEX IDX_BIH_ORIGINAL_ID  ON BUCKET_INSTANCE_HISTORY(ORIGINAL_ID);
CREATE INDEX IDX_BIH_SERVICE_ID   ON BUCKET_INSTANCE_HISTORY(SERVICE_ID);
CREATE INDEX IDX_BIH_BATCH_ID     ON BUCKET_INSTANCE_HISTORY(BATCH_ID);
CREATE INDEX IDX_BIH_ARCHIVED_AT  ON BUCKET_INSTANCE_HISTORY(ARCHIVED_AT);

COMMENT ON TABLE BUCKET_INSTANCE_HISTORY
    IS 'Audit history of BUCKET_INSTANCE rows deleted by the scheduler.';
